---
  - name: "My first playbook"
    hosts: localhost

    tasks:
      - name: "test reachability"
        ping:
      - name: "install stress"
        community.general.homebrew:
          name: stress
          state: present
