name: ansible-lint
on:
  push:
    main
  pull_request:

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - name: Setup developer environment
        run: |
          ansible-galaxy collection install community.general

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          path: "playbooks/"
